//
//  ValidatePinCodeRouter.swift
//  validate_pincode
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ValidatePinCodeRouter {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ValidatePinCodeViewController(nibName: nil, bundle: nil)
        let interactor = ValidatePinCodeInteractor()
        let router = ValidatePinCodeRouter()
        let presenter = ValidatePinCodePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}

extension ValidatePinCodeRouter: ValidatePinCodeWireframeProtocol {
    
    func routeToMain() {
        self.viewController?.dismiss(animated: true)
    }
    
}
