//
//  ValidatePinCodeProtocols.swift
//  validate_pincode
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ValidatePinCodeWireframeProtocol: class {
    func routeToMain()
}
//MARK: Presenter -
protocol ValidatePinCodePresenterProtocol: class {
    func notifyViewDidLoaded()
    func notifyRouteToMain()
}

//MARK: Interactor -
protocol ValidatePinCodeInteractorProtocol: class {
    var presenter: ValidatePinCodePresenterProtocol?  { get set }
}

//MARK: View -
protocol ValidatePinCodeViewProtocol: class {
    var presenter: ValidatePinCodePresenterProtocol?  { get set }
    func displayInputTextFieldEmpty()
}
