//
//  MainInteractor.swift
//  validate_pincode
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainInteractor {

    weak var presenter: MainPresenterProtocol?
}

extension  MainInteractor: MainInteractorProtocol {
    
}
