//
//  MainRouter.swift
//  validate_pincode
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainRouter {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MainViewController(nibName: nil, bundle: nil)
        let interactor = MainInteractor()
        let router = MainRouter()
        let presenter = MainPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}

extension MainRouter: MainWireframeProtocol {
    
    func routeToValidatePinCode() {
        let validatePinCodePage = UINavigationController(rootViewController: ValidatePinCodeRouter.createModule())
        validatePinCodePage.modalPresentationStyle = .fullScreen
        self.viewController?.present(validatePinCodePage, animated: true, completion: nil)
    }
    
}
